### ISSUE TITLE
'=' formatting with spaces

### ISSUE THREAD

**Issue by derdav3** [olivierverdier/python-latex-highlighting#2] opened 2017-05-01 16:07 UTC
if I write a = 3 with spaces around the '=' character it reformats it to 'a =3'

I'm not that experienced with latex packages, but I though I let you know

**Comment by olivierverdier** [comment] 2017-05-01 16:10
I do not have this problem. Can you be more specific?

**Comment by derdav3** [comment] 2017-05-01 16:15
ehm ok I try:
`\begin{python}[caption=Variable initialization]
graph = tensorflow.Graph()
with graph.as_default():
	var = tensorflow.Variable(1)
\end{python}`

results in:
![bildschirmfoto 2017-05-01 um 18 14 37](https://cloud.githubusercontent.com/assets/6107913/25585291/1927093c-2e9a-11e7-9b83-5905cc38feeb.png)

**Comment by olivierverdier** [comment] 2017-05-01 16:17
I tried the same code, no problem. It could be a conflict with another package, or caused by an older LaTeX installation?

**Comment by olivierverdier** [comment] 2017-05-01 16:38
As I can't reproduce the error, I'm closing this issue for now. Feel free to reopen if you think that it is a bug in this package.

**Closed by olivierverdier** 2017-05-01 16:38 UTC

**Comment by LittleNewton** [comment] 2019-05-03 18:47
Hey. I encountered this problem. May I show you all the details of my TeX source code after publishing?
